name: Build Binaries

on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Deps
      run: sudo apt-get install libluajit-5.1-dev
      if: ${{ matrix.os != 'macos-latest' }}
    - name: Deps
      run: |
        wget https://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz
        tar xvf LuaJIT-2.1.0-beta3.tar.gz
        cd LuaJIT-2.1.0-beta3
        make install MACOSX_DEPLOYMENT_TARGET=10.14
      if: ${{ matrix.os == 'macos-latest' }}
    - name: Build
      uses: marcopolo/cargo@master
      with:
        command: build
        args: --release --lib
        working-directory: rust
    - name: Copy
      run: cp rust/target/release/libfilter.dylib rust/target/release/libfilter.so
      if: ${{ matrix.os == 'macos-latest' }}
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: rust/target/release/libfilter.so
        asset_name: ${{ matrix.os }}-libfilter.so
        asset_content_type: application/octet-stream
